### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by yingwei13mei** [amusi/daily-question#1]
关于Logistic回归和SVM，以下说法错误的是？

A. Logistic回归可用于预测事件发生概率的大小 
B. Logistic回归的目标函数是最小化后验概率 
C. SVM的目标的结构风险最小化 
D. SVM可以有效避免模型过拟合 

答案：B，Logit回归本质上是一种根据样本对权值进行极大似然估计的方法，而后验概率正比于先验概率和似然函数的乘积。logit仅仅是最大化似然函数，并没有最大化后验概率，更谈不上最小化后验概率。A错误 Logit回归的输出就是样本属于正类别的几率，可以计算出概率，正确C. SVM的目标是找到使得训练数据尽可能分开且分类间隔最大的超平面，应该属于结构风险最小化. D. SVM可以通过正则化系数控制模型的复杂度，避免过拟合。

**Comment by amusi** [comment]
好的，预计加入第12题

**Comment by qlibp** [comment]
不知道这道题是怎么来的，如果是自己编写的话，建议D选项的表述改一下。因为答案解释跟选项表述不完全一致。我们不能说，SVM因为可以加入正则项，进而减少过拟合的可能性，所以SVM算法自身就可以有效避免过拟合。

选项表述为：存在某种方法可使得SVM算法有效避免模型过拟合，可能更佳？

拙见请指教。

**Comment by amusi** [comment]
谢谢提醒，已经修改了
