### ISSUE TITLE
四道

### ISSUE THREAD

**Issue by yingwei13mei** [amusi/daily-question#2]
一、在有监督学习中， 我们如何使用聚类方法？ 
1. 我们可以先创建聚类类别， 然后在每个类别上用监督学习分别进行学习
2. 我们可以使用聚类“类别id”作为一个新的特征项， 然后再用监督学习分别进行学习
3. 在进行监督学习之前， 我们不能新建聚类类别
4. 我们不可以使用聚类“类别id”作为一个新的特征项， 然后再用监督学习分别进行学习
A. 2 和 4
B. 1 和 2
C. 3 和 4
D. 1 和 3
答案 ：B--猜是B

二、下列选项不是SVM核函数的是：
A.多项式核函数
B.logistic核函数
C.径向基核函数
D.Sigmoid核函数

答案：B

三、决策树的父节点和子节点的熵的大小关系是什么？
A. 决策树的父节点更大
B. 子节点的熵更大
C. 两者相等
D. 根据具体情况而定

答案：A

四、关于排序算法的以下说法，错误的是______。
A.快速排序的平均时间复杂度为O（nlogn），最坏时间复杂度为O（n2）
B.堆排序的平均时间复杂度为O（nlogn），最坏时间复杂度为O（nlogn） 
C.冒泡排序的平均时间复杂度为O（n2），最坏时间复杂度为O（n2）
D.归并排序的平均时间复杂度为O（nlogn），最坏时间复杂度为O（n2）

答案：D

**Comment by amusi** [comment]
感谢补充
